"""split insider and insider trades

Revision ID: 5515ef02093e
Revises: 00db96ed24b0
Create Date: 2018-05-18 11:32:23.632753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5515ef02093e'
down_revision = '00db96ed24b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insider_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insider_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(length=100), nullable=True),
    sa.Column('last_date', sa.DateTime(), nullable=True),
    sa.Column('transaction_type', sa.String(length=100), nullable=True),
    sa.Column('owner_type', sa.String(length=20), nullable=True),
    sa.Column('shares_traded', sa.Integer(), nullable=True),
    sa.Column('last_price', sa.Float(precision=4), nullable=True),
    sa.Column('shares_held', sa.Integer(), nullable=True),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['insider_id'], ['insiders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('insiders_ticker_id_fkey', 'insiders', type_='foreignkey')
    op.drop_column('insiders', 'last_price')
    op.drop_column('insiders', 'relation')
    op.drop_column('insiders', 'transaction_type')
    op.drop_column('insiders', 'last_date')
    op.drop_column('insiders', 'shares_traded')
    op.drop_column('insiders', 'shares_held')
    op.drop_column('insiders', 'owner_type')
    op.drop_column('insiders', 'ticker_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insiders', sa.Column('ticker_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('insiders', sa.Column('owner_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('insiders', sa.Column('shares_held', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('insiders', sa.Column('shares_traded', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('insiders', sa.Column('last_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('insiders', sa.Column('transaction_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('insiders', sa.Column('relation', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('insiders', sa.Column('last_price', sa.REAL(), autoincrement=False, nullable=True))
    op.create_foreign_key('insiders_ticker_id_fkey', 'insiders', 'tickers', ['ticker_id'], ['id'], ondelete='CASCADE')
    op.drop_table('insider_trades')
    # ### end Alembic commands ###
