version: '2.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
  app:
    build: .
    ports:
       - "5000:5000"
    depends_on:
      db:
        condition: service_started
